type CompositeResourceDefinition implements Node & KubernetesResource {
  id: ID!

  apiVersion: String!
  kind: String!
  metadata: ObjectMeta!
  spec: CompositeResourceDefinitionSpec!
  status: CompositeResourceDefinitionStatus

  raw: JSONObject!

  events: EventConnection! @goField(forceResolver: true)
  definedCompositeResources(version: String): CompositeResourceConnection! @goField(forceResolver: true)
  definedCompositeResourceClaims(version: String, namespace: String): CompositeResourceClaimConnection! @goField(forceResolver: true)
}

type CompositeResourceConnection {
  nodes: [CompositeResource!]
  totalCount: Int!
}

type CompositeResourceClaimConnection {
  nodes: [CompositeResourceClaim!]
  totalCount: Int!
}

type CompositeResourceDefinitionSpec {
  group: String!
  names: CompositeResourceDefinitionNames!
  claimNames: CompositeResourceDefinitionNames
  connectionSecretKeys: [String!]
  defaultComposition: Composition @goField(forceResolver: true)
  enforcedComposition: Composition @goField(forceResolver: true)
  versions: [CompositeResourceDefinitionVersion!]
}

type CompositeResourceDefinitionNames {
  plural: String!
  singular: String
  shortNames: [String!]
  kind: String!
  listKind: String
  categories: [String!]
}

type CompositeResourceDefinitionVersion {
  name: String!
  referenceable: Boolean!
  served: Boolean!
  schema: CompositeResourceValidation
}

type CompositeResourceValidation {
  openAPIV3Schema: JSONObject
}

type CompositeResourceDefinitionStatus implements ConditionedStatus {
  conditions: [Condition!]
  controllers: CompositeResourceDefinitionControllerStatus
}

type CompositeResourceDefinitionControllerStatus {
  compositeResourceType: TypeReference
  compositeResourceClaimType: TypeReference
}

type TypeReference {
  apiVersion: String!
  kind: String!
}

type Composition implements Node & KubernetesResource {
  id: ID!

  apiVersion: String!
  kind: String!
  metadata: ObjectMeta!
  spec: CompositionSpec!
  status: CompositionStatus

  raw: JSONObject!

  events: EventConnection! @goField(forceResolver: true)
}

type CompositionSpec {
  compositeTypeRef: TypeReference!
  writeConnectionSecretsToNamespace: String

  # TODO(negz): Model patch sets and resource templates.
}

type CompositionStatus implements ConditionedStatus {
  conditions: [Condition!]
}

