type ManagedResource implements Node & KubernetesResource {
  id: ID!

  apiVersion: String!
  kind: String!
  metadata: ObjectMeta!
  spec: ManagedResourceSpec!
  status: ManagedResourceStatus!

  raw: JSONObject!

  events: EventConnection! @goField(forceResolver: true)
}

type ManagedResourceSpec {
  connectionSecret: Secret @goField(forceResolver: true)
  providerConfig: ProviderConfig @goField(forceResolver: true)
  deletionPolicy: DeletionPolicy
}

enum DeletionPolicy {
  DELETE
  ORPHAN
}

type ManagedResourceStatus implements ConditionedStatus {
  conditions: [Condition!]
}
