type Query {
    providers: ProviderConnection!
    configurations: ConfigurationConnection!
    compositeResourceDefinitions(dangling: Boolean = false): CompositeResourceDefinitionConnection!
    compositions(dangling: Boolean = false): CompositionConnection!
}

type ProviderConnection {
    nodes: [Provider!]
    totalCount: Int!
}

type ConfigurationConnection {
    nodes: [Configuration!]
    totalCount: Int!
}

type CompositeResourceDefinitionConnection {
    nodes: [CompositeResourceDefinition!]
    totalCount: Int!
}

type CompositionConnection {
    nodes: [Composition!]
    totalCount: Int!
}